Update pipenv requirements generation instructions
vmware/repository-service-tuf-api pull request #124
Opened 2022-10-13 18:07 UTC by MVrachev

With the new pipenv version there is no more a "--requirements" argument and now instead is "pipenv requirements > requirements.txt"

The same is about "dev" requirements.
Now the new command is:
"pipenv requirements --dev > dev-requirements.txt"

Also, add a test for that in `tox.ini`.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

2022-10-13 18:27 UTC, kairoaraujo requested changes
Sorry, but I notice it now.
Not sure if it can be done in another way. Anyway, if there is, we can raise a new issue for it and apply my suggestions.

2022-10-13 18:27 UTC, kairoaraujo commented on tox.ini
> +    3.10: py310,pep8,lint
```suggestion
    3.10: py310,pep8,lint,requirements,test,test-doc
```

2022-10-13 18:27 UTC, kairoaraujo commented on tox.ini
>      3.9: py39,pep8,lint
```suggestion
    3.9: py39,pep8,lint,requirements,test,test-doc
```

2022-10-17 18:16 UTC, MVrachev commented
I rebased on main and followed your suggestions.

2022-10-18 06:03 UTC, kairoaraujo approved these changes
LGTM

2022-10-18 06:04 UTC, kairoaraujo commented
Thank you, @MVrachev. I am merging it.

2022-10-18 06:04 UTC, merged