fix: custom redis configuration for the container
vmware/repository-service-tuf-api pull request #206
Opened 2022-12-15 09:51 UTC by kairoaraujo

The current custom Redis configuration for the RSTUF API container doesn't work correctly.

- Fix wrong parsing for the Dynaconf configuration. The parser included the Dynaconf `envvar_prefix` `RSTUF`.
- Fix documentation
  - More detail about choosing a specific port for the celery task's backend result.
  - Remove invalid parameter for RSTUF API

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

2022-12-20 08:13 UTC, kairoaraujo commented
@MVrachev, it's ready now. I fixed the name to be aligned with RSTUF Worker.

2022-12-20 15:34 UTC, MVrachev requested changes
Good!
Only one small sentence should be fixed.

2022-12-20 15:34 UTC, MVrachev commented on docs/source/guide/Docker_README.md
> +This settings are shared to Repository Workers
Nit:
```suggestion
These settings are shared with the repository workers
```

2022-12-21 05:44 UTC, MVrachev approved these changes

2022-12-21 05:44 UTC, merged