Add an option to add task_id to target custom
vmware/repository-service-tuf-api pull request #219
Opened 2023-01-10 21:46 UTC by MVrachev

Add an option which can be used for debugging to add the "task_id" of the process that adds the target into the "custom" attributes of all targets.
By default this option is enabled as it will add a small overhead, but can be quite useful for debugging in a bad scenario.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

2023-01-17 12:27 UTC, kairoaraujo requested changes

2023-01-18 14:22 UTC, MVrachev commented
Ready for another review.

2023-01-23 19:35 UTC, kairoaraujo requested changes
Can you please exclude the `docs/source/_static` from this PR.
I know this isn't very pleasant, but I will check how to build those diagrams in another way.

2023-01-24 20:28 UTC, kairoaraujo approved these changes

2023-01-25 14:53 UTC, MVrachev commented
Can we merge this one or do we want someone else to see it as well?

2023-01-25 14:57 UTC, merged